# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a78b64cd663a0be92a08308fd3c782ebf6882c2e6d119abb33ee8bd19031882f271c07f1218914f474556fffd4b2117c371b44138993ce86594c2de4c1e296cf

test:
  secret_key_base: d974fe6be7da372389c4302f703e9a36b5f45958e628d16b5a551aec776f1f4f6b4b1fd36e20b2d53b9e8fa5252793773279861e19df6a8e0f928086c475f654

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
